"""
djanorm: A Django-like ORM with synchronous and asynchronous support.

Quick start:

    import dorm

    dorm.configure(
        DATABASES={
            'default': {
                'ENGINE': 'sqlite',
                'NAME': 'db.sqlite3',
            }
        },
        INSTALLED_APPS=['myapp'],
    )

    class Author(dorm.Model):
        name = dorm.CharField(max_length=100)
        age  = dorm.IntegerField()

    # Sync
    author = Author.objects.create(name='Alice', age=30)
    authors = Author.objects.filter(age__gte=18).order_by('name')

    # Async
    async def main():
        author = await Author.objects.acreate(name='Bob', age=25)
        author = await Author.objects.aget(name='Bob')
"""

from .conf import configure, parse_database_url, settings
from . import signals, transaction
from .db.connection import ahealth_check, health_check, pool_stats
from .signals import (
    Signal,
    post_delete,
    post_query,
    post_save,
    pre_delete,
    pre_query,
    pre_save,
)
from .exceptions import (
    DatabaseError,
    DoesNotExist,
    FieldDoesNotExist,
    ImproperlyConfigured,
    IntegrityError,
    MigrationError,
    MultipleObjectsReturned,
    OperationalError,
    ProtectedError,
    ValidationError,
)
from .expressions import Exists, F, OuterRef, Q, Subquery, Value
from .aggregates import (
    ArrayAgg,
    Avg,
    Count,
    Max,
    Min,
    StdDev,
    StringAgg,
    Sum,
    Variance,
)
from .functions import (
    Abs,
    Case,
    Cast,
    Coalesce,
    Concat,
    DenseRank,
    Extract,
    ExtractDay,
    ExtractHour,
    ExtractMinute,
    ExtractMonth,
    ExtractSecond,
    ExtractWeek,
    ExtractWeekDay,
    ExtractYear,
    FirstValue,
    Greatest,
    Lag,
    LastValue,
    Lead,
    Least,
    Length,
    Lower,
    NTile,
    Now,
    Rank,
    Replace,
    Round,
    RowNumber,
    StrIndex,
    Substr,
    Trunc,
    TruncDate,
    TruncDay,
    TruncHour,
    TruncMinute,
    TruncMonth,
    TruncQuarter,
    TruncWeek,
    TruncYear,
    Upper,
    When,
    Window,
)
from .constraints import CheckConstraint, UniqueConstraint
from .fields import (
    ArrayField,
    AutoField,
    BigAutoField,
    BigIntegerField,
    BigIntegerRangeField,
    BinaryField,
    BooleanField,
    CharField,
    CITextField,
    CompositePrimaryKey,
    DateField,
    DateRangeField,
    DateTimeField,
    DateTimeRangeField,
    DecimalField,
    DecimalRangeField,
    DurationField,
    EmailField,
    EnumField,
    FileField,
    FloatField,
    ImageField,
    ForeignKey,
    GeneratedField,
    GenericIPAddressField,
    IPAddressField,
    IntegerField,
    IntegerRangeField,
    JSONField,
    ManyToManyField,
    NullBooleanField,
    OneToOneField,
    PositiveIntegerField,
    PositiveSmallIntegerField,
    Range,
    RangeField,
    SlugField,
    SmallAutoField,
    SmallIntegerField,
    TextField,
    TimeField,
    URLField,
    UUIDField,
    CASCADE,
    PROTECT,
    SET_NULL,
    SET_DEFAULT,
    DO_NOTHING,
    RESTRICT,
)
from .storage import (
    ContentFile,
    FieldFile,
    File,
    FileSystemStorage,
    Storage,
    default_storage,
    get_storage,
    reset_storages,
)
from .models import Model
from .manager import Manager
from .indexes import Index
from .queryset import CTE, CombinedQuerySet, CursorPage, Prefetch, QuerySet, RawQuerySet
from .validators import (
    EmailValidator,
    MaxLengthValidator,
    MaxValueValidator,
    MinLengthValidator,
    MinValueValidator,
    RegexValidator,
    validate_email,
)

__version__ = "2.3.1"
__all__ = [
    # Config
    "configure",
    "parse_database_url",
    "settings",
    "transaction",
    "signals",
    "health_check",
    "ahealth_check",
    "pool_stats",
    # Signals
    "Signal",
    "pre_save",
    "post_save",
    "pre_delete",
    "post_delete",
    "pre_query",
    "post_query",
    # Base
    "Model",
    "Manager",
    "QuerySet",
    "CombinedQuerySet",
    "CursorPage",
    "CTE",
    "Prefetch",
    "RawQuerySet",
    # Fields
    "AutoField",
    "BigAutoField",
    "SmallAutoField",
    "CompositePrimaryKey",
    "CharField",
    "TextField",
    "IntegerField",
    "SmallIntegerField",
    "BigIntegerField",
    "PositiveIntegerField",
    "PositiveSmallIntegerField",
    "FloatField",
    "DecimalField",
    "BooleanField",
    "NullBooleanField",
    "DateField",
    "TimeField",
    "DateTimeField",
    "EmailField",
    "URLField",
    "SlugField",
    "UUIDField",
    "IPAddressField",
    "GenericIPAddressField",
    "JSONField",
    "BinaryField",
    "ArrayField",
    "GeneratedField",
    "DurationField",
    "EnumField",
    "CITextField",
    "FileField",
    "ImageField",
    # Storage
    "Storage",
    "FileSystemStorage",
    "File",
    "ContentFile",
    "FieldFile",
    "default_storage",
    "get_storage",
    "reset_storages",
    "Range",
    "RangeField",
    "IntegerRangeField",
    "BigIntegerRangeField",
    "DecimalRangeField",
    "DateRangeField",
    "DateTimeRangeField",
    "ForeignKey",
    "OneToOneField",
    "ManyToManyField",
    # on_delete constants
    "CASCADE",
    "PROTECT",
    "SET_NULL",
    "SET_DEFAULT",
    "DO_NOTHING",
    "RESTRICT",
    # Expressions
    "Q",
    "F",
    "Value",
    "Subquery",
    "Exists",
    "OuterRef",
    # Aggregates
    "Count",
    "Sum",
    "Avg",
    "Max",
    "Min",
    "StdDev",
    "Variance",
    # PG-only aggregates
    "StringAgg",
    "ArrayAgg",
    # Functions
    "Case",
    "When",
    "Coalesce",
    "Now",
    "Concat",
    "Cast",
    "Upper",
    "Lower",
    "Length",
    "Abs",
    "Greatest",
    "Least",
    "Round",
    "Trunc",
    "TruncDate",
    "TruncDay",
    "TruncWeek",
    "TruncMonth",
    "TruncQuarter",
    "TruncYear",
    "TruncHour",
    "TruncMinute",
    "Extract",
    "ExtractYear",
    "ExtractMonth",
    "ExtractDay",
    "ExtractHour",
    "ExtractMinute",
    "ExtractSecond",
    "ExtractWeekDay",
    "ExtractWeek",
    "Substr",
    "Replace",
    "StrIndex",
    # Window functions
    "Window",
    "RowNumber",
    "Rank",
    "DenseRank",
    "NTile",
    "Lag",
    "Lead",
    "FirstValue",
    "LastValue",
    # Constraints
    "CheckConstraint",
    "UniqueConstraint",
    # Index
    "Index",
    # Validators
    "MinValueValidator",
    "MaxValueValidator",
    "MinLengthValidator",
    "MaxLengthValidator",
    "RegexValidator",
    "EmailValidator",
    "validate_email",
    # Exceptions
    "DoesNotExist",
    "MultipleObjectsReturned",
    "FieldDoesNotExist",
    "ValidationError",
    "DatabaseError",
    "IntegrityError",
    "ProtectedError",
    "OperationalError",
    "MigrationError",
    "ImproperlyConfigured",
]
