"""Tree / graph helpers built on top of recursive CTEs.

The :class:`~dorm.queryset.CTE` primitive already lets users hand-
craft a ``WITH RECURSIVE`` body. This module ships idiomatic helpers
for the two patterns that show up in 95% of real schemas:

- **Descendants of a node** — given an adjacency list keyed by a
  self-referential FK (``parent_id``), return every transitive
  child.
- **Ancestors of a node** — the same recursion in the opposite
  direction.

Both helpers compose with regular querysets via ``.raw(...)`` /
``.with_cte(...)``: the helper gives you back a SQL string and a
``params`` list ready to splice into a query, plus a convenience
shortcut that returns a fully-built queryset.

PG and SQLite both support ``WITH RECURSIVE``; MySQL ≥ 8 does too.
``UNION ALL`` semantics differ slightly (PG accepts cycles via
``CYCLE`` clause; SQLite doesn't) — for cycle-prone graphs use the
``cycle_field`` knob to ask for a ``visited`` array column.
"""

from __future__ import annotations

from typing import Any

from .conf import _validate_identifier
from .queryset import CTE


def _quote(name: str, kind: str) -> str:
    _validate_identifier(name, kind=kind)
    return f'"{name}"'


def descendants_cte(
    model: Any,
    *,
    parent_field: str,
    root_pk: Any,
    fields: list[str] | None = None,
    pk_column: str = "id",
    cte_name: str = "descendants",
    cycle_field: str | None = None,
) -> CTE:
    """Build a :class:`CTE` whose rows are every descendant of
    ``root_pk`` in *model*'s adjacency list (rooted at the row whose
    PK equals ``root_pk``).

    Args:
        model: the dorm Model whose table backs the tree.
        parent_field: the self-referential FK column (typically the
            ``<name>_id`` form generated by
            :class:`~dorm.fields.ForeignKey`).
        root_pk: the PK value to start the walk from.
        fields: columns to project. Defaults to ``[pk_column,
            parent_field]``.
        pk_column: the PK column name. Defaults to ``"id"``.
        cte_name: identifier for the CTE inside the surrounding
            statement. Defaults to ``"descendants"``.
        cycle_field: when set, adds a ``visited`` array column and a
            cycle-detection clause that stops the recursion at the
            first repeated PK. Useful for cyclic graphs (PG only —
            SQLite has no array literal).
    """
    table = _quote(model._meta.db_table, kind="descendants_cte table")
    pk = _quote(pk_column, kind="descendants_cte pk_column")
    parent = _quote(parent_field, kind="descendants_cte parent_field")
    proj = list(fields or [pk_column, parent_field])
    proj_sql = ", ".join(_quote(f, kind="descendants_cte field") for f in proj)
    base_proj = ", ".join(f"r.{_quote(f, kind='descendants_cte field')}" for f in proj)

    if cycle_field is None:
        sql = (
            f"SELECT {proj_sql} FROM {table} WHERE {pk} = %s "
            f"UNION ALL "
            f"SELECT {base_proj} FROM {table} r "
            f"JOIN {_quote(cte_name, kind='descendants_cte name')} d "
            f"ON r.{parent} = d.{pk}"
        )
        params: list[Any] = [root_pk]
    else:
        cycle = _quote(cycle_field, kind="descendants_cte cycle_field")
        sql = (
            f"SELECT {proj_sql}, ARRAY[{pk}] AS {cycle}, FALSE AS is_cycle "
            f"FROM {table} WHERE {pk} = %s "
            f"UNION ALL "
            f"SELECT {base_proj}, d.{cycle} || r.{pk}, r.{pk} = ANY(d.{cycle}) "
            f"FROM {table} r "
            f"JOIN {_quote(cte_name, kind='descendants_cte name')} d "
            f"ON r.{parent} = d.{pk} "
            f"WHERE NOT d.is_cycle"
        )
        params = [root_pk]

    return CTE(sql, params=params, recursive=True)


def ancestors_cte(
    model: Any,
    *,
    parent_field: str,
    leaf_pk: Any,
    fields: list[str] | None = None,
    pk_column: str = "id",
    cte_name: str = "ancestors",
) -> CTE:
    """Build a recursive CTE that walks **upward** from ``leaf_pk``
    along ``parent_field`` until ``parent_field`` is ``NULL``.

    See :func:`descendants_cte` for argument semantics."""
    table = _quote(model._meta.db_table, kind="ancestors_cte table")
    pk = _quote(pk_column, kind="ancestors_cte pk_column")
    parent = _quote(parent_field, kind="ancestors_cte parent_field")
    proj = list(fields or [pk_column, parent_field])
    proj_sql = ", ".join(_quote(f, kind="ancestors_cte field") for f in proj)
    base_proj = ", ".join(f"r.{_quote(f, kind='ancestors_cte field')}" for f in proj)
    name_q = _quote(cte_name, kind="ancestors_cte name")

    sql = (
        f"SELECT {proj_sql} FROM {table} WHERE {pk} = %s "
        f"UNION ALL "
        f"SELECT {base_proj} FROM {table} r "
        f"JOIN {name_q} a ON a.{parent} = r.{pk}"
    )
    return CTE(sql, params=[leaf_pk], recursive=True)


def descendants(
    model: Any,
    *,
    parent_field: str,
    root_pk: Any,
    pk_column: str = "id",
    using: str = "default",
):
    """Convenience: return a list of dicts ``{pk_column, parent_field}``
    representing every descendant of ``root_pk``. Equivalent to
    building :func:`descendants_cte` and consuming it via raw SQL.

    For richer column projections, build the CTE directly and stitch
    it into your own ``with_cte()``-shaped queryset."""
    cte = descendants_cte(
        model,
        parent_field=parent_field,
        root_pk=root_pk,
        pk_column=pk_column,
    )
    from .db.connection import get_connection

    conn = get_connection(using)
    pk = _quote(pk_column, kind="descendants pk_column")
    parent = _quote(parent_field, kind="descendants parent_field")
    cte_q = _quote("descendants", kind="descendants name")

    if conn.vendor == "postgresql":
        sql = (
            f"WITH RECURSIVE {cte_q} AS ({cte.sql}) "
            f"SELECT {pk} AS pk, {parent} AS parent_id FROM {cte_q} "
            f"WHERE {pk} <> %s ORDER BY {pk}"
        )
        params = list(cte.params) + [root_pk]
    else:
        sql = (
            f"WITH RECURSIVE {cte_q} AS ({cte.sql}) "
            f"SELECT {pk} AS pk, {parent} AS parent_id FROM {cte_q} "
            f"WHERE {pk} <> ? ORDER BY {pk}"
        )
        # SQLite uses ? placeholders; cte.sql already uses %s so we
        # rewrite the body to ?-style for the SQLite path.
        sql = sql.replace("%s", "?")
        params = list(cte.params) + [root_pk]
    return conn.execute(sql, params)


def ancestors(
    model: Any,
    *,
    parent_field: str,
    leaf_pk: Any,
    pk_column: str = "id",
    using: str = "default",
):
    """Convenience inverse of :func:`descendants`. Returns rows from
    the leaf upward (root last)."""
    cte = ancestors_cte(
        model,
        parent_field=parent_field,
        leaf_pk=leaf_pk,
        pk_column=pk_column,
    )
    from .db.connection import get_connection

    conn = get_connection(using)
    pk = _quote(pk_column, kind="ancestors pk_column")
    parent = _quote(parent_field, kind="ancestors parent_field")
    cte_q = _quote("ancestors", kind="ancestors name")

    if conn.vendor == "postgresql":
        sql = (
            f"WITH RECURSIVE {cte_q} AS ({cte.sql}) "
            f"SELECT {pk} AS pk, {parent} AS parent_id FROM {cte_q} "
            f"WHERE {pk} <> %s"
        )
        params = list(cte.params) + [leaf_pk]
    else:
        sql = (
            f"WITH RECURSIVE {cte_q} AS ({cte.sql}) "
            f"SELECT {pk} AS pk, {parent} AS parent_id FROM {cte_q} "
            f"WHERE {pk} <> ?"
        )
        sql = sql.replace("%s", "?")
        params = list(cte.params) + [leaf_pk]
    return conn.execute(sql, params)


__all__ = [
    "ancestors",
    "ancestors_cte",
    "descendants",
    "descendants_cte",
]
